### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by workinprogressgh** [mrwigster/constant_bot#1]
run with python gives this error:
$ python bom.py
Traceback (most recent call last):
  File "bom.py", line 13, in <module>
    bot = Bot(comments_file="comments.txt", blacklist="blacklist.txt")
TypeError: __init__() got an unexpected keyword argument 'blacklist'

run with python3 gives this error:

$ python3 bom.py 
Traceback (most recent call last):
  File "bom.py", line 2, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'

**Comment by mrwigster** [comment]
Did you run `pip install schedule`?

**Comment by workinprogressgh** [comment]
Yes I did.

and still getting this : 

Traceback (most recent call last):
  File "schedul.py", line 13, in <module>
    bot = Bot(comments_file="comments.txt", blacklist="blacklist.txt")
TypeError: __init__() got an unexpected keyword argument 'blacklist'

**Comment by workinprogressgh** [comment]
Alright I have managed to get it working; this is what I did

I changed line 13 from this:
bot = Bot(comments_file="comments.txt", blacklist="blacklist.txt")
to that: 
bot = Bot(comments_file="comments.txt") # , blacklist="blacklist.txt")

I don't know if this will have a effect on the job9 or what happens later.... 
for now this is the massage I've seen for the 20 minutes: 

2019-01-23 00:07:48,821 - INFO - Logged-in successfully as 'twerking_slayers' using the cookie!
2019-01-23 00:07:48,823 - INFO - Constant Bot-Leave running 24/7

maybe the info will show later, its staked ...
